{ src: `https://listingslab.com/public/svg/avatars/Dapper.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Punk.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Hippy.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Rasta.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Rocker.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Biker.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Hipster.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Mumma.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Chix.svg` },

		{ src: `https://listingslab.com/public/svg/device/000000/Android.svg` },	
		{ src: `https://listingslab.com/public/svg/device/000000/MacOS.svg` },
		{ src: `https://listingslab.com/public/svg/device/000000/iPhone.svg` },	
		{ src: `https://listingslab.com/public/svg/device/000000/Desktop.svg` },

		{ src: `https://listingslab.com/public/jpg/avatars/ali.jpg` },
		{ src: `https://listingslab.com/public/jpg/avatars/biden.jpg`},
		{ src: `https://listingslab.com/public/jpg/avatars/boris.jpg`},
		{ src: `https://listingslab.com/public/jpg/avatars/colz.jpg` },
		{ src: `https://listingslab.com/public/jpg/avatars/scomo.jpg` },
		{ src: `https://listingslab.com/public/jpg/avatars/weizang.jpg` },
		{ src: `https://listingslab.com/public/svg/coloured/Google.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Duck.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Smiley.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Commercify.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/PiJS.svg` },
		{ src: `https://listingslab.com/public/svg/avatars/Smiley/Light.svg` },
		{ src: `https://listingslab.com/public/svg/flags/cn.svg` },	
		{ src: `https://listingslab.com/public/svg/flags/gb.svg` },	
		{ src: `https://listingslab.com/public/png/avatars/Sharky.png` },